name: Benchmarks

on:
  pull_request:
  push:
    branches:
      - main
      - benchmarking

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run pytest-benchmark benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Python setup
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # Install build dependencies
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel poetry pre-commit

      # Install package
      - name: Install
        id: install
        run: poetry install

      # Run benchmark
      - name: Run benchmark
        run: poetry run pytest tests/integration/benchmark.py --benchmark-json output.json

      # Store results
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '120%'
          comment-on-alert: true
          comment-always: true
          fail-on-alert: true
          alert-comment-cc-users: '@limx0'
