name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest]
        python-version: [ "3.9", "3.10" ]
    name: build - Python ${{ matrix.python-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      # Python setup
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install build dependencies
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel poetry pre-commit
          poetry config experimental.new-installer false

      # Run pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files

      # install
      - name: Install
        id: install
        run: poetry install

      # Run tests
      - name: Run tests
        run: poetry run pytest
